logger:   &logger
    file:       pca2_linearsvm.results
    level:      info
exs:
    # FIndiaM vs FBrazilBH - no preproc
    - eyefitting:   &eyefitting
        size:       [128,128]
      feature:      
        name:       &feature PCASK 
        n_components:    250
      classifier:   &classifier 
        name:       SVMSK
        kernel:     linear

      crossvalidation: &xvalid
        k:          6
        test_size:  0.2
        vgsize:     3

      classes: &classes
        - city:     Mumbai
          country:  India
          id:       0
          gender:   1
          n:        500

        - city:     Belo Horizonte
          country:  Brazil
          id:       1
          gender:   1
          n:        500


    - eyefitting:   *eyefitting
      feature:      
        name:       *feature
        n_components:    300
      classifier:   *classifier 
      crossvalidation: *xvalid
      classes: *classes

    - eyefitting:   *eyefitting
      feature:      
        name:       *feature
        n_components:    350
      classifier:   *classifier 
      crossvalidation: *xvalid
      classes: *classes

    - eyefitting:   *eyefitting
      feature:      
        name:       *feature
        n_components:    400
      classifier:   *classifier 
      crossvalidation: *xvalid
      classes: *classes

    - eyefitting:   *eyefitting
      feature:      
        name:       *feature
        n_components:    450
      classifier:   *classifier 
      crossvalidation: *xvalid
      classes: *classes

    - eyefitting:   *eyefitting
      feature:      
        name:       *feature
        n_components:    500
      classifier:   *classifier 
      crossvalidation: *xvalid
      classes: *classes

    - eyefitting:   *eyefitting
      feature:      
        name:       *feature
        n_components:    550
      classifier:   *classifier 
      crossvalidation: *xvalid
      classes: *classes

    - eyefitting:   *eyefitting
      feature:      
        name:       *feature
        n_components:    600
      classifier:   *classifier 
      crossvalidation: *xvalid
      classes: *classes
