logger:   &logger
    file:       pca3_linearsvm.results
    level:      info
exs:
    # FIndiaM vs FBrazilBH - no preproc
    - eyefitting:   &eyefitting
        size:       [128,128]
      feature:      
        name:       &feature PCASK 
        n_components:    250
      classifier:   &classifier 
        name:       SVMSK
        kernel:     linear

      crossvalidation: &xvalid
        k:          6
        test_size:  0.2
        vgsize:     3

      classes: &classes
        - city:     Mumbai
          country:  India
          id:       0
          gender:   1
          n:        500

        - city:     Belo Horizonte
          country:  Brazil
          id:       1
          gender:   1
          n:        500


    - eyefitting:   *eyefitting
      feature:      
        name:       *feature
        n_components:    650
      classifier:   *classifier 
      crossvalidation: *xvalid
      classes: *classes

    - eyefitting:   *eyefitting
      feature:      
        name:       *feature
        n_components:    700
      classifier:   *classifier 
      crossvalidation: *xvalid
      classes: *classes

    - eyefitting:   *eyefitting
      feature:      
        name:       *feature
        n_components:    750
      classifier:   *classifier 
      crossvalidation: *xvalid
      classes: *classes

    - eyefitting:   *eyefitting
      feature:      
        name:       *feature
        n_components:    800
      classifier:   *classifier 
      crossvalidation: *xvalid
      classes: *classes

    - eyefitting:   *eyefitting
      feature:      
        name:       *feature
        n_components:    850
      classifier:   *classifier 
      crossvalidation: *xvalid
      classes: *classes

    - eyefitting:   *eyefitting
      feature:      
        name:       *feature
        n_components:    900
      classifier:   *classifier 
      crossvalidation: *xvalid
      classes: *classes

    - eyefitting:   *eyefitting
      feature:      
        name:       *feature
        n_components:    950
      classifier:   *classifier 
      crossvalidation: *xvalid
      classes: *classes
