logger:   &logger
    file:       sh_linearsvm_150and150.results
    level:      info
exs:
    # FIndiaM vs FBrazilBH - no preproc
    - eyefitting:   &eyefitting
        size:       [128,128]
      feature:      
        name:       &feature SpatialHistogram
        sz:         [4,4]
      classifier:   &classifier 
        name:       SVMSK
        kernel:     linear

      crossvalidation: &xvalid
        k:          6
        test_size:  0.2
        vgsize:     3

      classes: &classes
        - city:     Mumbai
          country:  India
          id:       0
          gender:   1
          n:        150

        - city:     Belo Horizonte
          country:  Brazil
          id:       1
          gender:   1
          n:        150


    - eyefitting:   *eyefitting
      feature:      
        name:       *feature
        sz:         [8,8]
      classifier:   *classifier 
      crossvalidation: *xvalid
      classes: *classes

    - eyefitting:   *eyefitting
      feature:      
        name:       *feature
        sz:         [12,12]
      classifier:   *classifier 
      crossvalidation: *xvalid
      classes: *classes

    - eyefitting:   *eyefitting
      feature:      
        name:       *feature
        sz:         [16,16]
      classifier:   *classifier 
      crossvalidation: *xvalid
      classes: *classes

    - eyefitting:   *eyefitting
      feature:      
        name:       *feature
        sz:         [20,20]
      classifier:   *classifier 
      crossvalidation: *xvalid
      classes: *classes

    - eyefitting:   *eyefitting
      feature:      
        name:       *feature
        sz:         [24,24]
      classifier:   *classifier 
      crossvalidation: *xvalid
      classes: *classes

    - eyefitting:   *eyefitting
      feature:      
        name:       *feature
        sz:         [28,28]
      classifier:   *classifier 
      crossvalidation: *xvalid
      classes: *classes

    - eyefitting:   *eyefitting
      feature:      
        name:       *feature
        sz:         [32,32]
      classifier:   *classifier 
      crossvalidation: *xvalid
      classes: *classes
