logger:   &logger
    file:       sh_linearsvmC1_3class128m_500.results
    level:      info
exs:
    # FIndiaM vs FBrazilBH - no preproc
    - eyefitting:   &eyefitting
        size:       [128,128]
      feature:      
        name:       &feature SpatialHistogram
        sz:         [4,4]
      classifier:   &classifier 
        name:       SVMSK
        kernel:     linear
        C:          1

      crossvalidation: &xvalid
        k:          6
        test_size:  0.2
        vgsize:     3

      classes: &classes
        - city:     Mumbai
          country:  India
          id:       0
          gender:   0
          n:        500

        - city:     Belo Horizonte
          country:  Brazil
          id:       1
          gender:   0
          n:        500

        - city:     Guadalajara
          country:  Mexico
          id:       2
          gender:   0
          n:        500
