exs:
    # FIndiaM vs FBrazilBH - no preproc
    - eyefitting:   &eyefitting
        size:       [128,128]
      feature:      
        name:       PCASK
        n_components:    25
      classifier:   &classifier 
        name:       NearestNeighbor
        k:          5

      crossvalidation: &xvalid
        k:          6
        test_size:  0.2
        vgsize:     3

      classes: &classes
        - city:     Mumbai
          country:  India
          id:       0
          gender:   1
          n:        50

        - city:     Belo Horizonte
          country:  Brazil
          id:       1
          gender:   1
          n:        50

    - eyefitting:   *eyefitting
      feature:      
        name:       PCASK
        n_components:    50
      classifier:   *classifier 
      crossvalidation: *xvalid
      classes: *classes

    - eyefitting:   *eyefitting
      feature:      
        name:       PCASK
        n_components:    75
      classifier:   *classifier 
      crossvalidation: *xvalid
      classes: *classes

    - eyefitting:   *eyefitting
      feature:      
        name:       PCASK
        n_components:    100
      classifier:   *classifier 
      crossvalidation: *xvalid
      classes: *classes

    - eyefitting:   *eyefitting
      feature:      
        name:       PCASK
        n_components:    125
      classifier:   *classifier 
      crossvalidation: *xvalid
      classes: *classes

    - eyefitting:   *eyefitting
      feature:      
        name:       PCASK
        n_components:    150
      classifier:   *classifier 
      crossvalidation: *xvalid
      classes: *classes

    - eyefitting:   *eyefitting
      feature:      
        name:       PCASK
        n_components:    175
      classifier:   *classifier 
      crossvalidation: *xvalid
      classes: *classes

    - eyefitting:   *eyefitting
      feature:      
        name:       PCASK
        n_components:    200
      classifier:   *classifier 
      crossvalidation: *xvalid
      classes: *classes
